// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEgpBAITlZfG1mHxRBOC0eQwxlLtwZrlI',
    appId: '1:743127979068:web:6aa4585878772c6ca39f39',
    messagingSenderId: '743127979068',
    projectId: 'scanify-devlopment',
    authDomain: 'scanify-devlopment.firebaseapp.com',
    storageBucket: 'scanify-devlopment.appspot.com',
    measurementId: 'G-DV29PLGLCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjsjQPeYTFHqO4F1DpDgD1S3CXdYW-ZBQ',
    appId: '1:743127979068:android:378501b5af770780a39f39',
    messagingSenderId: '743127979068',
    projectId: 'scanify-devlopment',
    storageBucket: 'scanify-devlopment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU5tU83QcjvL11ow73-9OFG8O_qZI5UDk',
    appId: '1:743127979068:ios:c6a30a7234cf0546a39f39',
    messagingSenderId: '743127979068',
    projectId: 'scanify-devlopment',
    storageBucket: 'scanify-devlopment.appspot.com',
    iosClientId: '743127979068-5hr5r7us3mer55c9e7h2hkdl61f0g2pj.apps.googleusercontent.com',
    iosBundleId: 'ml.sivasai.inventoryScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU5tU83QcjvL11ow73-9OFG8O_qZI5UDk',
    appId: '1:743127979068:ios:2de46b947ed0f965a39f39',
    messagingSenderId: '743127979068',
    projectId: 'scanify-devlopment',
    storageBucket: 'scanify-devlopment.appspot.com',
    iosClientId: '743127979068-1dnb35ueb090qkj7o55ps5c09q35fppe.apps.googleusercontent.com',
    iosBundleId: 'ml.sivasai.inventoryScanner.RunnerTests',
  );
}
